cas_guard:

     # Enter the hostname of the CAS server.
    hostname:             'sso.stage.uga.edu'

    # REQUEST_PATH of the CAS server.
    url:                  cas/login 

    # Route node.
    route:

        # Name of your home route.
        homepage:

        # Name of your login route.
        login:

        # Name of the route where user is redirected after successful logout.
        logout:

    # Version of the CAS Server.
    version:              '2.0'

    # Logout node.
    logout:

        # Are the CAS server and your application supporting single sign out signal?
        supported:            true # Example: false

        # true if you want to provide the url to the user to go back to your application after logout.
        redirect_url:         false # Example: true