cas:
    base_url: https://sso.stage.uga.edu/cas
    protocol:
        login:
            path: /login
            allowed_parameters:
                - service
                - renew
                - gateway
            default_parameters:
                service: https://beta.sustain.uga.edu/user/profile
        serviceValidate:
            path: /serviceValidate
            allowed_parameters:
                - service
                - pgtUrl
                - renew
                - format
            default_parameters:
                format: JSON
                #pgtUrl: cas_bundle_proxy_callback
        logout:
            path: /logout
            allowed_parameters:
                - service
            default_parameters:
                service: https://beta.sustain.uga.edu/
#        proxy:
#            path: /proxy
#            allowed_parameters:
#                - targetService
#                - pgt
#        proxyValidate:
#            path: /p3/proxyValidate
#            allowed_parameters:
#                - service
#                - ticket
#                - pgtUrl
#                - format
#            default_parameters:
#                format: JSON
#                #pgtUrl: cas_bundle_proxy_callback
